// ui/src/view/Login.tsx
import { useLogin } from "../lib/api";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import axios from "axios";

const Login = () => {
  const { mutate } = useLogin();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const navigate = useNavigate();

  const doLogin = async () => {
    try {
      await axios.post("/login", {
        username,
        password,
      });
      toast.success("logged in");
      await mutate();
      navigate("/");
    } catch {}
  };

  const doRegister = async () => {
    try {
      await axios.post("/register", {
        username,
        password,
      });
      toast.success("registered and logged in");
      await mutate();
      navigate("/");
    } catch {}
  };

  return (
    <form>
      <div className="form-item">
        <label>ユーザ名</label>
        <input
          type="text"
          placeholder="kurenaif"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          required
        />
      </div>

      <div className="form-item">
        <label>パスワード</label>
        <input
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />
      </div>

      <div>
        <button onClick={() => doLogin()}>ログイン</button>
        <button style={{marginLeft: '1em', display: 'inline-block'}} onClick={() => doRegister()}>登録</button>
      </div>
    </form>
  );
};
export default Login;

// frontend/src/view/Login.svelte
<script lang="ts">
  import axios from "axios";
  import { loginuser } from "../lib/stores.ts";
  import { Login } from "../lib/schema.ts";

  let username = '';
  let password = '';

  const login = async () => {
    const res = await axios.post("/login", {
      username: username,
      password: password,
    }, {
      withCredentials: true,
    })
    const data = await Login.parse(res.data)
    loginuser.update(() => data);
  }

  const register = () => {
    axios.post("/register", {
      username: username,
      password: password,
    }, {
      withCredentials: true,
    })
  }
</script>

<div>
  <form>
    <div>
      <label>ユーザ名</label>
      <input type="text" placeholder="kurenaif" bind:value={username} required>
    </div>

    <div>
      <label>パスワード</label>
      <input type="password" bind:value={password} required>
    </div>

    <div>
      <input type="button" value="ログイン" on:click={login} />
      <input type="button" value="登録" on:click={register} />
    </div>
  </form>
</div>

<style>
label {
  display: block;
  font-size: 75%;
  font-weight: bold;
}
</style>
